services:
  vpn:
    privileged: true
    user: root
    # image: ghcr.io/jsoliveir/openvpn
    build:
      context: .
      dockerfile: .ci/Dockerfile
    ports:
      - 1194:1194/udp
      - 7505:7505/tcp
    volumes:
      # persist ssl certificates
      - ./data/ssl:/app/ssl/keys
      # openvpn profile
      - ./data/profile:/app/client
      # authentication
      - ./auth:/app/auth
    environment:
      # Optional Variables
      
      VPN_AUTH_SCRIPT: /app/auth/microsoft.py
      VPN_CLIENT_PROFILE: /app/client/profile.ovpn
      VPN_SSL_CLIENT_CERT: /app/ssl/keys/client.crt
      VPN_SSL_CLIENT_KEY: /app/ssl/keys/client.key
      VPN_SSL_SERVER_CERT: /app/ssl/keys/server.crt
      VPN_SSL_SERVER_KEY: /app/ssl/keys/server.key
      VPN_SSL_CA_CERT: /app/ssl/keys/ca.crt
      VPN_SSL_CA_KEY: /app/ssl/keys/ca.key
      # Not mandatory but useful 
      VPN_NETWORK_MASK: 255.255.255.0
      VPN_SERVER_HOST: 127.0.0.1
      VPN_NETWORK_ADDR: 10.0.0.0
      VPN_SERVER_PORT: 1194
      VPN_CLIENT_PROFILE_NAME: VPN
      VPN_SERVER_OPTIONS: |
        push "route 168.63.129.16"
        push "route 10.0.0.0 255.0.0.0"
        push "dhcp-option DNS 168.63.129.16"
        push "dhcp-option WINS 168.63.129.16"
        push "dhcp-option domain example.com"
        push "dhcp-option domain windows.net"
  

